"""Prompt template used by agent/explainer.py to compose the final justified recommendation.

The LLM is only ever asked to produce *text* (reasoning, labels, a reply, season-plan
descriptions) — every number in the final response (profit, ROI, yield, weather
readings) comes straight from the tool outputs and is merged in afterward, never
generated by the model. This keeps the "never invent numbers" system-prompt rule
enforceable in code, not just in instructions.
"""

RESPONSE_SCHEMA_HINT = """Respond with a JSON object of exactly this shape:
{
  "reply": "<one short, friendly paragraph summarizing the recommendation for the farmer>",
  "crops": [
    {
      "crop_name": "<copied verbatim from input>",
      "suitability": "<'Excellent fit' | 'Good fit' | 'Moderate fit' | 'Risky fit'>",
      "risk_level": "<'Low' | 'Medium' | 'High'>",
      "reasoning": "<2-3 sentences citing the retrieved evidence and weather given below>"
    }
  ],
  "season_plan": {
    "land_preparation": "<1 sentence>",
    "sowing": "<1 sentence>",
    "fertilizer": "<1 sentence>",
    "irrigation": "<1 sentence>",
    "pest_checks": "<1 sentence>",
    "harvest": "<1 sentence>"
  }
}"""


def build_explanation_prompt(
    profile: dict,
    weather: dict | None,
    per_crop_evidence: list[dict],
    message: str,
) -> tuple[str, str]:
    """per_crop_evidence: list of {"crop_name", "rag_passages", "finance_summary"}, already
    ordered with the top recommendation first — that ordering is non-negotiable and must be
    reflected consistently across "reply", "crops", and "season_plan"."""
    top_crop_name = per_crop_evidence[0]["crop_name"] if per_crop_evidence else ""
    system = (
        "You are writing the final crop recommendation for a Bangladeshi farmer, replying "
        "directly to their latest message. Use ONLY the retrieved evidence, weather data, and "
        "financial figures given below to justify each recommendation — do not invent facts or "
        "numbers.\n\n"
        f'The top recommendation has already been decided: "{top_crop_name}". You must not '
        f"contradict this — do not name a different crop as the primary/best choice anywhere "
        f'in "reply". The "crops" array must list "{top_crop_name}" first, in the same order '
        f'given below. The "season_plan" must describe cultivating "{top_crop_name}" '
        f"specifically — every stage must reference {top_crop_name}, not any other crop.\n\n"
        "If the farmer's message asks about or names a specific crop, open your \"reply\" by "
        "directly addressing that — confirm whether it's the one being recommended, or explain "
        "briefly why a different one was chosen instead. Don't ignore what they actually asked.\n\n"
        + RESPONSE_SCHEMA_HINT
    )

    weather_str = (
        f"Temperature {weather['temperature']}C, humidity {weather['humidity']}%, "
        f"recent rainfall {weather['rainfall']}mm, location {weather['location']}."
        if weather
        else "No weather data available."
    )

    evidence_blocks = []
    for item in per_crop_evidence:
        passages = "\n    ".join(item["rag_passages"]) or "(no passages retrieved)"
        evidence_blocks.append(
            f"- {item['crop_name']}:\n"
            f"    Retrieved evidence:\n    {passages}\n"
            f"    Financial summary: {item['finance_summary']}"
        )
    evidence_str = "\n".join(evidence_blocks)

    user = (
        f"Farmer's latest message: {message!r}\n\n"
        f"Farmer profile: {profile}\n\n"
        f"Weather: {weather_str}\n\n"
        f"Candidate crops and evidence:\n{evidence_str}\n\n"
        "Return the JSON object now, covering all candidate crops listed above in the same order."
    )
    return system, user
